#!/bin/bash
### ---
### name: 'MULTIQC'
### container: 'nextflow/rnaseq-nf'
### outputs:
### - 'multiqc_report.html'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/3c/e600dd6713da5d689f608fd30a2d7c/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 -e "NXF_TASK_WORKDIR" -v /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work:/Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work -w "$NXF_TASK_WORKDIR" -u $(id -u):$(id -g) --name $NXF_BOXID nextflow/rnaseq-nf /bin/bash -ue /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/3c/e600dd6713da5d689f608fd30a2d7c/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f fastqc_gut_logs
    rm -f liver
    rm -f fastqc_lung_logs
    rm -f fastqc_liver_logs
    ln -s /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/83/45e31a11e486bd67dd9d1bd916913c/fastqc_gut_logs fastqc_gut_logs
    ln -s /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/48/417e58ea794adf7e4ea321c0858998/liver liver
    ln -s /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/43/0cec4fc70e4002fcf6f21454420e31/fastqc_lung_logs fastqc_lung_logs
    ln -s /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/6b/6e2ed19f6e11ea098b95dd4720c360/fastqc_liver_logs fastqc_liver_logs
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/nadyanovichkova/Projects/PhenoBiome2025/final-project/part2/work/3c/e600dd6713da5d689f608fd30a2d7c/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
